# Generated by Django 4.2.16 on 2026-02-21 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cv_adapter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('job_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Aplicado'), ('screening', 'Triagem RH'), ('interview_1', '1ª Entrevista'), ('interview_2', '2ª Entrevista'), ('technical', 'Teste Técnico'), ('offer', 'Oferta Recebida'), ('rejected', 'Reprovado'), ('withdrawn', 'Desistência'), ('ghosted', 'Sem Retorno')], default='applied', max_length=30)),
                ('data_aplicacao', models.DateField(auto_now_add=True)),
                ('data_atualizacao', models.DateField(auto_now=True)),
                ('link_vaga', models.URLField(blank=True)),
                ('notas', models.TextField(blank=True)),
                ('salario_estimado', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv_adaptation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_entries', to='cv_adapter.jobapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tracked Application',
                'verbose_name_plural': 'Tracked Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
