# Generated by Django 4.2.16 on 2026-02-27 14:22

import apps.cv_adapter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_adapter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvbase',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.cv_adapter.models.cv_upload_path),
        ),
    ]
