# Generated by Django 4.2.16 on 2026-03-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_adapter', '0002_make_cvbase_file_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='linkedin_message',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
